/*
<Additional SELECT - Option>
*/
--<1> ORACLE
SELECT STUDENT_NAME 학생이름,
       STUDENT_ADDRESS 주소지
FROM TB_STUDENT;


--<2> ORACLE
SELECT STUDENT_NAME , 
       STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN='Y'
ORDER BY STUDENT_SSN DESC;

--<3> ORACLE
SELECT STUDENT_NAME 학생이름,
       STUDENT_NO 학번,
       STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1)='9'
AND   STUDENT_ADDRESS LIKE '%경기도%'
OR    STUDENT_ADDRESS LIKE '%강원도%';


--<4> ORACLE

SELECT PROFESSOR_NAME,
       PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = ( SELECT DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '법학과');
--<5> ORACLE
SELECT STUDENT_NO , 
       POINT
FROM TB_GRADE
WHERE SUBSTR(TERM_NO,1)='200402'
AND   CLASS_NO = 'C3118100'
ORDER BY POINT DESC,
      STUDENT_NO ASC;

--<6> ORACLE
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT S,TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO
ORDER BY STUDENT_NAME ASC;

--<6>ANSI
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;


--<7> ORACLE
SELECT CLASS_NAME, 
       DEPARTMENT_NAME
FROM TB_DEPARTMENT D,
     TB_CLASS C
WHERE D.DEPARTMENT_NO = C.DEPARTMENT_NO;

--<7> ANSI
SELECT CLASS_NAME, 
       DEPARTMENT_NAME
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO);

--<8>ORACLE
SELECT CLASS_NAME, 
       PROFESSOR_NAME
       PROFESSOR_NO
FROM TB_PROFESSOR P,
     TB_CLASS_PROFESSOR C,
     TB_CLASS C1
WHERE P.PROFESSOR_NO = C.PROFESSOR_NO
AND   C.CLASS_NO = C1.CLASS_NO
ORDER BY PROFESSOR_NAME ASC;

--<8>ANSI

SELECT CLASS_NAME, 
       PROFESSOR_NAME
       PROFESSOR_NO
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO)
ORDER BY PROFESSOR_NAME ASC;
       
--<9>ORACLE
SELECT CLASS_NAME, 
       PROFESSOR_NAME
FROM TB_PROFESSOR P,
     TB_CLASS_PROFESSOR C,
     TB_CLASS C1,
     TB_DEPARTMENT D
WHERE P.PROFESSOR_NO = C.PROFESSOR_NO
AND   C.CLASS_NO = C1.CLASS_NO
AND   D.DEPARTMENT_NO = P.DEPARTMENT_NO
AND   D.CATEGORY = '인문사회'
ORDER BY CLASS_NAME ASC;

--<9>ANSI 
SELECT CLASS_NAME, 
       PROFESSOR_NAME,
       P.DEPARTMENT_NO
FROM TB_PROFESSOR P
JOIN TB_CLASS_PROFESSOR  USING(PROFESSOR_NO)
JOIN TB_CLASS  USING(CLASS_NO)
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

--<10> 
SELECT G.STUDENT_NO 학번,
       S.STUDENT_NAME "학생 이름",
       TRUNC(AVG(POINT),1)
FROM TB_STUDENT S, 
     TB_GRADE G,
     TB_DEPARTMENT D
WHERE G.STUDENT_NO = S.STUDENT_NO
AND   S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND   D.DEPARTMENT_NAME = '음악학과'
GROUP BY G.STUDENT_NO ,S.STUDENT_NAME;

--ANSI
SELECT STUDENT_NO 학번,
       STUDENT_NAME "학생 이름",
       TRUNC(AVG(POINT),1)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO ,STUDENT_NAME;


--11
SELECT DEPARTMENT_NAME, 
       STUDENT_NAME, 
       PROFESSOR_NAME
FROM TB_STUDENT S,
     TB_DEPARTMENT D,
     TB_PROFESSOR P
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO
AND   S.COACH_PROFESSOR_NO=P.PROFESSOR_NO(+)
AND   S.STUDENT_NO = 'A313047';

--ANSI
SELECT DEPARTMENT_NAME, 
       STUDENT_NAME, 
       PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO=PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

     
--12
SELECT STUDENT_NAME, 
       TERM_NO
FROM TB_STUDENT S,
     TB_CLASS C,
     TB_GRADE G
WHERE G.STUDENT_NO = S.STUDENT_NO
AND   G.CLASS_NO  = C.CLASS_NO
AND   SUBSTR(TERM_NO,1,4)='2007'
AND   CLASS_NAME = '인간관계론';

--ANSI       
SELECT STUDENT_NAME, 
       TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4)='2007'
AND   CLASS_NAME = '인간관계론';

--<13>
SELECT C.CLASS_NAME,
       D.DEPARTMENT_NAME,
       CP.PROFESSOR_NO
FROM TB_CLASS C, 
     TB_DEPARTMENT D,
     TB_CLASS_PROFESSOR CP
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
AND   C.CLASS_NO = CP.CLASS_NO(+)
AND   D.CATEGORY ='예체능'
AND   PROFESSOR_NO IS NULL;

--ANSI
SELECT CLASS_NAME,
       DEPARTMENT_NAME,
       PROFESSOR_NO
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT OUTER JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
WHERE CATEGORY ='예체능'
AND PROFESSOR_NO IS NULL;

--<14>
SELECT STUDENT_NAME, 
       NVL(PROFESSOR_NAME,'미지정'),
       DEPARTMENT_NAME
FROM TB_STUDENT S,
     TB_PROFESSOR P,
     TB_DEPARTMENT D
WHERE S.COACH_PROFESSOR_NO=P.PROFESSOR_NO(+)
AND   S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND   DEPARTMENT_NAME='서반아어학과';

--ANSI
SELECT STUDENT_NAME, 
       NVL(PROFESSOR_NAME,'미지정')
       DEPARTMENT_NAME
FROM TB_STUDENT S
LEFT OUTER JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME='서반아어학과';

--<15>
SELECT S.STUDENT_NO,
       S.STUDENT_NAME,
       D.DEPARTMENT_NAME,
       TRUNC(AVG(POINT),1)
FROM TB_STUDENT S,
     TB_DEPARTMENT D,
     TB_GRADE G
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO
AND   S.STUDENT_NO = G.STUDENT_NO
AND   ABSENCE_YN!='Y'
GROUP BY S.STUDENT_NO,S.STUDENT_NAME,D.DEPARTMENT_NAME
HAVING AVG(POINT)>=4;

--ANSI
SELECT STUDENT_NO,
       STUDENT_NAME,
       DEPARTMENT_NAME,
       TRUNC(AVG(POINT),1)
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO=D.DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN !='Y'
GROUP BY STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT)>=4;

--<16>ORACLE
SELECT C.CLASS_NO,
       C.CLASS_NAME,
       D.DEPARTMENT_NAME,
       TRUNC(AVG(G.POINT),1)
FROM TB_CLASS C,
     TB_GRADE G,
     TB_DEPARTMENT D
WHERE C.CLASS_NO = G.CLASS_NO
AND   C.DEPARTMENT_NO = D.DEPARTMENT_NO
AND   D.DEPARTMENT_NAME='환경조경학과'
AND   C.CLASS_TYPE='전공선택'
GROUP BY C.CLASS_NO,C.CLASS_NAME,D.DEPARTMENT_NAME;
     
--ANSI
SELECT CLASS_NO,
       CLASS_NAME,
       TRUNC(AVG(POINT),1)
FROM TB_CLASS 
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME='환경조경학과'
AND   CLASS_TYPE='전공선택'
GROUP BY CLASS_NO,CLASS_NAME;

--<17>
SELECT STUDENT_NAME,
       STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');
--ANSI  SAME

--<18>
SELECT S.STUDENT_NO,S.STUDENT_NAME
FROM TB_STUDENT S,
     TB_DEPARTMENT D,
     TB_GRADE G
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO
AND   S.STUDENT_NO = G.STUDENT_NO
AND DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NO,S.STUDENT_NAME
HAVING AVG(POINT)=(SELECT  MAX(AVG(POINT))
FROM TB_STUDENT S,
     TB_DEPARTMENT D,
     TB_GRADE G
WHERE S.DEPARTMENT_NO=D.DEPARTMENT_NO
AND   S.STUDENT_NO = G.STUDENT_NO
AND DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NAME);

--
--ANSI 

SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO,STUDENT_NAME
HAVING AVG(POINT)=(SELECT MAX(AVG(POINT))
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NAME
);

/*
SELECT  TRUNC(AVG(POINT),1)
FROM TB_DEPARTMENT D,
     TB_GRADE G,
     TB_CLASS C
WHERE CATEGORY = (SELECT CATEGORY
                  FROM TB_DEPARTMENT
                  WHERE DEPARTMENT_NAME='환경조경학과')

GROUP BY C.CLASS_NO;
*/

SELECT D.DEPARTMENT_NAME,
       TRUNC(AVG(POINT),1)
FROM TB_DEPARTMENT D,
     TB_CLASS C,
     TB_GRADE G
WHERE D.DEPARTMENT_NO = C.DEPARTMENT_NO
AND   C.CLASS_NO = G.CLASS_NO
AND D.CATEGORY = (SELECT CATEGORY
                  FROM TB_DEPARTMENT
                  WHERE DEPARTMENT_NAME='환경조경학과')
GROUP BY D.DEPARTMENT_NAME                 
ORDER BY D.DEPARTMENT_NAME;

                  
    

    
    

